

spring:
  cloud:
    config:
      server:
        git:
          uri: git@github.com:amasucci/configurations-examples.git
          clone-on-start: true
          basedir: ~/configs
logging:
  level:
    org:
      springframework:
        cloud: INFO
#encrypt:
#  key: super_secret_symmetric_key
